<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQEoA9lx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQEoA9lx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQEoA9lx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQEoA9lx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQEoA9lx\App_KernelDevDebugContainer([
    'container.build_hash' => 'QEoA9lx',
    'container.build_id' => 'd22166c1',
    'container.build_time' => 1665927996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQEoA9lx');
