<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNS4B4Q9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNS4B4Q9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNS4B4Q9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNS4B4Q9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNS4B4Q9\App_KernelDevDebugContainer([
    'container.build_hash' => 'NS4B4Q9',
    'container.build_id' => '1bb8d5a5',
    'container.build_time' => 1665938916,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNS4B4Q9');
